# version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: coulsontl/domain-reverse-proxy
    network_mode: bridge
    restart: always
    ports:
      - '5000:5000'
      - '5001:5001'
    environment:
      - TZ=Asia/Shanghai
      - PROXY_URL=http://user:password@yourproxy:port
      - SERVER_PORT_5000=https://site1.com
      - SERVER_PORT_5001=https://site1.com